version: '3.8'
services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_value:/static
      - media_value:/media
    restart: always
    depends_on:
      - django_admin

  django_admin:
    build:
      context: ./app
    container_name: django_admin
    volumes:
      - static_value:/code/static
      - media_value:/code/media
      - ./nginx:/code/conf/
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  bot:
    build:
      context: ./app
    container_name: tg_bot
    command: python manage.py bot
    depends_on:
      - db
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./.env

  db:
    image: postgres:12.4
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env

volumes:
  postgres_data:
  static_value:
  media_value:
