# Generated by Django 4.0.2 on 2022-02-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("moderator", "Модератор")],
                default="user",
                help_text="Укажите роль",
                max_length=250,
                verbose_name="Роль пользователя",
            ),
        ),
    ]
