name: Styles

on: [push, pull_request]

jobs:
  formatter:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1


    - name: Install dependencies
      run: pip install black==22.1.0

    - name: Test with black
      run: |
        cd app/
        python -m black .
